name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRET }}" # Ensure it's set in repo secrets
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
      
      - name: Build page
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Adjust if your build output directory differs

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
        with:
          fields: repo,commit,author,job,took

    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379

    # steps:
    #   - name: Install redis cli
    #     run: sudo apt-get update -y && sudo apt-get install redis-tools -y
      
    #   - name: Test redis
    #     run: redis-cli -h localhost -p 6379 ping

    #   - name: Print variable
    #     run: echo "${{secrets.TOKEN_SECRET}}"

    #   - name: setup
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: '18' 